import { AnimatePresence, motion } from "framer-motion";
import { X, Gauge, Orbit, AlertTriangle } from "lucide-react";
import { useSatellite } from "../../hooks/useRiskData";
import { Skeleton } from "../ui";
import { ProbabilityBar, RiskBadge } from "./RiskVisuals";

interface Props {
  noradId: number | null;
  onClose: () => void;
}

export default function SatelliteDrawer({ noradId, onClose }: Props) {
  const open = noradId !== null;
  const { data, isLoading, isError } = useSatellite(noradId);

  return (
    <AnimatePresence>
      {open && (
        <>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 z-40 bg-space-bg/70 backdrop-blur-sm"
          />
          <motion.div
            initial={{ x: "100%" }}
            animate={{ x: 0 }}
            exit={{ x: "100%" }}
            transition={{ type: "spring", damping: 28, stiffness: 260 }}
            className="fixed right-0 top-0 z-50 h-full w-full max-w-md border-l border-space-border bg-space-panel/95 backdrop-blur-xl overflow-y-auto scrollbar-thin"
          >
            <div className="sticky top-0 z-10 flex items-center justify-between px-5 py-4 border-b border-space-border bg-space-panel/90 backdrop-blur-xl">
              <div className="flex items-center gap-2">
                <Orbit className="w-4 h-4 text-accent-cyan" />
                <h3 className="text-xs font-semibold tracking-widest text-slate-300 uppercase">
                  Satellite Detail
                </h3>
              </div>
              <button
                onClick={onClose}
                className="w-7 h-7 flex items-center justify-center rounded-lg text-slate-400 hover:text-white hover:bg-space-hover/50 transition-colors"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="p-5 space-y-5">
              {isLoading ? (
                <div className="space-y-3">
                  <Skeleton className="h-8 w-2/3" />
                  <Skeleton className="h-24 w-full" />
                  <Skeleton className="h-40 w-full" />
                </div>
              ) : isError || !data ? (
                <div className="flex items-center gap-2 text-sm text-status-critical py-8 justify-center">
                  <AlertTriangle className="w-4 h-4" />
                  Failed to load satellite detail.
                </div>
              ) : (
                <>
                  <div>
                    <p className="text-[10px] font-mono text-slate-500 uppercase tracking-widest">
                      NORAD {data.norad_id}
                    </p>
                    <h2 className="text-xl font-display font-semibold text-white mt-1">
                      {data.object_name}
                    </h2>
                    <div className="mt-3 flex items-center gap-3">
                      <RiskBadge probability={data.risk_probability} />
                      <span className="text-xs font-mono text-slate-400">
                        {(data.risk_probability * 100).toFixed(1)}% AI risk probability
                      </span>
                    </div>
                  </div>

                  <div className="glass-panel p-4">
                    <div className="flex items-center gap-2 mb-3">
                      <Gauge className="w-3.5 h-3.5 text-accent-blue" />
                      <span className="text-[10px] font-mono uppercase tracking-widest text-slate-500">
                        Model Risk Probability
                      </span>
                    </div>
                    <ProbabilityBar probability={data.risk_probability} />
                    <p className="mt-3 text-[11px] text-slate-500 leading-relaxed">
                      Prediction generated by the OrbitWatch risk model from the latest tracked
                      orbital elements for this object.
                    </p>
                  </div>

                  <div>
                    <p className="text-[10px] font-mono uppercase tracking-widest text-slate-500 mb-2">
                      Orbital Elements
                    </p>
                    <div className="grid grid-cols-2 gap-2">
                      <Field label="Altitude" value={fmt(data.altitude_km, "km")} />
                      <Field label="Inclination" value={fmt(data.inclination, "°")} />
                      <Field label="RAAN" value={fmt(data.raan, "°")} />
                      <Field label="Mean Motion" value={fmt(data.mean_motion, "rev/day")} />
                      <Field label="Eccentricity" value={fmt(data.eccentricity)} />
                      <Field label="BSTAR" value={fmt(data.bstar)} />
                    </div>
                  </div>
                </>
              )}
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}

function fmt(value: number | null | undefined, unit = "") {
  if (value === null || value === undefined) return "—";
  return `${value.toFixed(4)}${unit ? ` ${unit}` : ""}`;
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-space-border bg-space-bg/50 px-3 py-2">
      <p className="text-[9px] font-mono uppercase tracking-widest text-slate-500">{label}</p>
      <p className="text-sm font-mono text-slate-200 mt-0.5">{value}</p>
    </div>
  );
}
